# Generated by Django 3.2.7 on 2021-09-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_ansimgps'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsimDataset',
            fields=[
                ('lat', models.FloatField(max_length=300)),
                ('lon', models.FloatField(max_length=300)),
                ('ansimseq', models.IntegerField(primary_key=True, serialize=False)),
                ('statecode', models.IntegerField(blank=True, null=True)),
                ('statename', models.TextField(blank=True, null=True)),
                ('wardname', models.TextField(blank=True, null=True)),
                ('workplacename', models.TextField(blank=True, null=True)),
                ('owner', models.TextField(blank=True, null=True)),
                ('ansimdate', models.DateField(blank=True, null=True)),
                ('address1', models.TextField(blank=True, null=True)),
                ('address2', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('categorydetail', models.TextField(blank=True, null=True)),
                ('tel', models.TextField(blank=True, null=True)),
                ('isansim', models.TextField(blank=True, null=True)),
                ('cancledate', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('modifydate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AnsimGPS',
        ),
    ]
