# Generated by Django 3.2.6 on 2021-09-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_publicpdataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicpdataset',
            name='hetime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicpdataset',
            name='hstime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicpdataset',
            name='isfree',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicpdataset',
            name='setime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicpdataset',
            name='sstime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicpdataset',
            name='wetime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicpdataset',
            name='wstime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
