# Generated by Django 3.2.7 on 2021-10-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_publicpdataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlat', models.FloatField(max_length=300)),
                ('dlon', models.FloatField(max_length=300)),
            ],
        ),
    ]
