# Generated by Django 3.2.7 on 2021-10-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpdataset',
            name='dd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
