# Generated by Django 3.2.6 on 2021-09-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20210925_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicpdataset',
            name='agencycode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicpdataset',
            name='isfree',
            field=models.TextField(blank=True, null=True),
        ),
    ]
