# Generated by Django 3.2.6 on 2021-09-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20210925_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(max_length=300)),
                ('lon', models.FloatField(max_length=300)),
                ('ppid', models.TextField(blank=True, null=True)),
                ('ppname', models.TextField(blank=True, null=True)),
                ('ppcategory', models.TextField(blank=True, null=True)),
                ('ppcase', models.TextField(blank=True, null=True)),
                ('ppaddress1', models.TextField(blank=True, null=True)),
                ('ppaddress2', models.TextField(blank=True, null=True)),
                ('ppnum', models.IntegerField(blank=True, null=True)),
                ('gpgi', models.TextField(blank=True, null=True)),
                ('isdaysystem', models.TextField(blank=True, null=True)),
                ('opdays', models.TextField(blank=True, null=True)),
                ('wstime', models.DateField(blank=True, null=True)),
                ('wetime', models.DateField(blank=True, null=True)),
                ('sstime', models.DateField(blank=True, null=True)),
                ('setime', models.DateField(blank=True, null=True)),
                ('hstime', models.DateField(blank=True, null=True)),
                ('hetime', models.DateField(blank=True, null=True)),
                ('isfree', models.TextField(blank=True, null=True)),
                ('baseptime', models.IntegerField(blank=True, null=True)),
                ('basepfee', models.IntegerField(blank=True, null=True)),
                ('addutime', models.IntegerField(blank=True, null=True)),
                ('addifee', models.IntegerField(blank=True, null=True)),
                ('daypathtime', models.IntegerField(blank=True, null=True)),
                ('daypathfee', models.IntegerField(blank=True, null=True)),
                ('monthpathfee', models.IntegerField(blank=True, null=True)),
                ('paymeth', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('managementname', models.TextField(blank=True, null=True)),
                ('tel', models.TextField(blank=True, null=True)),
                ('modifydate', models.DateField(blank=True, null=True)),
                ('agencycode', models.TextField(blank=True, null=True)),
                ('agencyname', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PublicPDataset',
        ),
    ]
